version: 1.0.{build}
image: Visual Studio 2017
environment:
  CLI_VERSION: 2.0.0
  MYGET_API_KEY:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  NUGET_API_KEY:
    secure: 4WMsxFFj1s1R+uO8E96HqveIJM77lMWjcWhUnfpXslepnAMlPVigu/SPKnd4aCQn

build_script:
-  ps: ./build
test_script:
-  ps: ./test
artifacts:
  - path: 'Sharp*\**\Sharp*.nupkg'
  - path: 'SdkTests\SharpGen.Runtime\**\*.nupkg'

deploy_script:
- ps: ./deploy